<?php
/**
 * Settings schema and default content. Saved values in the `sh_settings` option are merged over this
 * (associative arrays merge key by key; lists such as repeaters are replaced as a whole).
 * Media fields hold attachment IDs (0 = not set); the demo importer fills them.
 */
defined('ABSPATH') || exit;

function sh_defaults() {
    static $d = null;
    if ($d !== null) return $d;
    $d = [
        'options' => [
            'custom_cursor' => true,
            'animations' => true,
            'gsap_desktop' => true,
            'gsap_mobile' => false,
            'preloader' => true,
            'preloader_assets' => ['logo' => true, 'video' => true, 'poster' => true, 'gallery' => true, 'fonts' => true, 'next_section' => true, 'warmup' => true],
            'video_quality' => '720p',
            'mobile_video_quality' => '480p',
            'logo' => 0,
            'demo_media_url' => 'https://raw.githubusercontent.com/AbdulHannanGit/saadhashmani-demo-media/main/manifest.json',
            'colors' => [
                'bg' => '#0b0b0c',
                'bg_raised' => '#121214',
                'bg_inset' => '#08080a',
                'tx' => '#f5f1ea',
                'tx_muted' => '#b0a89c',
                'tx_faint' => '#978f84',
                'glow' => '#f6f5f2',
                'line' => 'rgba(255,255,255,.08)',
                'line_strong' => 'rgba(255,255,255,.14)',
            ],
            'fonts' => [
                'grotesk_url' => 'https://api.fontshare.com/v2/css?f[]=zodiak@400,500,700&f[]=general-sans@400,500,600&display=swap',
                'google_url' => '',
                'local_heading' => 0,
                'local_body' => 0,
            ],
            'nav' => ['Home', 'The Record', 'Ventures', 'The Playbook', 'The Podcast', 'The Receipts', 'Contact'],
        ],
        'seo' => [
            'title' => 'Saad Hashmani — Investor · Operator · Mentor',
            'description' => 'Saad Hashmani: trader, entrepreneur and financial educator. From Karachi to Houston, built through execution, not theory.',
            'og_image' => 0,
        ],
        'hero' => [
            'eyebrow' => 'Investor · Operator · Mentor',
            'first_name' => 'Saad',
            'last_name' => 'Hashmani',
            'preloader_text' => 'LOADING · LOADING · LOADING · ',
            'scroll_text' => 'SCROLL TO UNLOCK · SCROLL TO UNLOCK · ',
            'poster' => 0,
            'video_480' => 0,
            'video_720' => 0,
            'video_1080' => 0,
            'clips' => '4.04, 5.04, 4.04, 5.04, 4.04, 5.04, 5, 5.04, 5, 5.04, 4.04, 5.04, 4.04, 5.04',
        ],
        'record' => [
            'eyebrow' => 'The Journey',
            'heading' => 'Built Through Execution, Not Theory',
            'stats' => [
                ['value' => '10yrs+', 'label' => 'Building businesses'],
                ['value' => '5M+', 'label' => 'Overall Audience'],
                ['value' => '1B+', 'label' => 'Platform Interactions'],
                ['value' => '900M+', 'label' => 'Net worth'],
            ],
            'timeline' => [
                [
                    'y' => '1989-2008',
                    't' => 'Karachi Roots',
                    'tag' => 'Origin',
                    'img' => 0,
                    'd' => 'Born in Karachi to a middle-class family that taught him early that "without education there is no way out." A tough school transfer became the fire behind a lifelong work ethic, and in 2008 he enrolled in mechanical engineering at NED University.',
                ],
                [
                    'y' => '2010-2013',
                    't' => 'A New Country',
                    'tag' => 'Foundation',
                    'img' => 0,
                    'd' => 'After 12 US visa rejections and one from the UK, the family finally emigrated to Texas, arriving with no house, no car, and no career. While studying engineering at Texas Tech, he built a first business from scratch: an eBay reselling operation that reached Top Rated Seller status before a brand dispute forced him to pivot to reselling used electronics door to door.',
                ],
                [
                    'y' => '2014-2015',
                    't' => 'The Phone Guys',
                    'tag' => 'Operator',
                    'img' => 0,
                    'd' => 'Left engineering unfinished at the end of 2013 despite a strong GPA, driving home overnight to start over. Opened his first retail store, The Phone Guys, then a second in Austin. Both ran at a loss for years while he lived frugally, saving and reinvesting every dollar.',
                ],
                [
                    'y' => '2016',
                    't' => 'The Breakthrough',
                    'tag' => 'Growth',
                    'img' => 0,
                    'd' => 'A franchise partnership turned the business around, the deal famously closed over a steak dinner in a rented suit and a rented car. The win opened the door to real estate expansion alongside a growing retail footprint across Texas.',
                ],
                [
                    'y' => '2021',
                    't' => 'Rebuilding From Zero',
                    'tag' => 'Resilience',
                    'img' => 0,
                    'd' => 'Everything he had built fell, from 100% to 40%. What followed was roughly two and a half years of genuine, unglamorous rebuilding, grounded this time in a decade of real operating experience rather than appearances.',
                ],
                [
                    'y' => '2024',
                    't' => 'Sharing The Knowledge',
                    'tag' => 'Education',
                    'img' => 0,
                    'd' => 'Launched The H University, a free skills and e-commerce education platform for aspiring entrepreneurs, funded out of pocket with a personal $100,000 investment and no donations taken.',
                ],
                [
                    'y' => '2025',
                    't' => 'Market Education',
                    'tag' => 'Trading',
                    'img' => 0,
                    'd' => 'Launched Trading Papa, a crypto and forex education platform built on a $300,000 investment, extending the mission from business skills to financial markets with free signals and live coaching.',
                ],
                [
                    'y' => '2026',
                    't' => 'Backing The Next Generation',
                    'tag' => 'Investing',
                    'img' => 0,
                    'd' => 'The H University surpassed 400,000 students. Now putting his own capital, banking relationships, and audience behind an SME investment collaboration to help fund and build the next wave of entrepreneurs.',
                ],
            ],
        ],
        'ventures' => [
            [
                'logo' => 0,
                'eyebrow' => 'Markets · Education',
                'title' => 'Trading Papa',
                'description' => 'A financial education platform focused on helping people understand trading concepts, market psychology, and disciplined decision-making.',
                'cta_label' => 'Explore Trading Papa',
                'cta_url' => 'https://tradingpapa.com/',
                'stats' => [
                    ['value' => '400k', 'label' => 'Students community'],
                    ['value' => '50k+', 'label' => 'Monthly traffic'],
                    ['value' => '24/7', 'label' => 'AI desk'],
                    ['value' => 'Daily', 'label' => 'Live calls'],
                ],
                'gallery' => [],
            ],
            [
                'logo' => 0,
                'eyebrow' => 'Education · Entrepreneurship',
                'title' => 'The H University',
                'description' => 'A learning platform built to help people develop practical digital skills, including e-commerce, business, technology, and online entrepreneurship.',
                'cta_label' => 'Explore The H University',
                'cta_url' => 'https://thehuniversity.com/',
                'stats' => [
                    ['value' => 'Global', 'label' => 'Learning community'],
                    ['value' => 'Multiple', 'label' => 'Skill categories'],
                    ['value' => 'Founder-led', 'label' => 'Practical education'],
                    ['value' => '1:1', 'label' => 'Founder-led'],
                ],
                'gallery' => [],
            ],
            [
                'logo' => 0,
                'eyebrow' => 'Retail · Houston',
                'title' => 'talk & txt',
                'description' => 'A Houston-based retail cellphone business that became one of the foundations of Saad\'s entrepreneurial journey.',
                'cta_label' => 'Connect with Saad',
                'cta_url' => '#',
                'stats' => [
                    ['value' => '2014', 'label' => 'Established'],
                    ['value' => 'Houston', 'label' => 'Texas'],
                    ['value' => 'Multi', 'label' => 'Store retail'],
                    ['value' => 'B2B', 'label' => 'Wholesale'],
                ],
                'gallery' => [],
            ],
            [
                'logo' => 0,
                'eyebrow' => 'Investments · Long-Term Vision',
                'title' => 'Real Estate',
                'description' => 'Building and exploring opportunities across businesses, real estate, technology, and emerging industries.',
                'cta_label' => 'Connect with Saad',
                'cta_url' => '#',
                'stats' => [
                    ['value' => 'Houston', 'label' => 'Home base'],
                    ['value' => 'Mixed', 'label' => 'Holdings'],
                    ['value' => 'Long', 'label' => 'Horizon'],
                    ['value' => 'GetAway', 'label' => 'Concept'],
                ],
                'gallery' => [],
            ],
        ],
        'partners' => [
            ['img' => 0, 'h' => 36, 'name' => 'Trading Papa'],
            ['img' => 0, 'h' => 32, 'name' => 'The H University'],
            ['img' => 0, 'h' => 22, 'name' => 'Partner'],
            ['img' => 0, 'h' => 22, 'name' => 'Partner'],
            ['img' => 0, 'h' => 22, 'name' => 'Partner'],
            ['img' => 0, 'h' => 24, 'name' => 'Daraz'],
            ['img' => 0, 'h' => 22, 'name' => 'Shopify'],
            ['img' => 0, 'h' => 20, 'name' => 'Bitget'],
            ['img' => 0, 'h' => 32, 'name' => 'Panthers'],
        ],
        'playbook' => [
            'eyebrow' => 'Founder Principles',
            'heading' => 'The Playbook',
            'locked_count' => 16,
            'reels' => [
                ['t' => 'Every business starts from zero', 'img' => 0, 'embed' => 'DddfD5cRyky'],
                ['t' => 'Karna kya hai?', 'img' => 0, 'embed' => 'DdjfsqvxMwg'],
                ['t' => 'Only you know your hard days', 'img' => 0, 'embed' => 'DdapOfDxwG0'],
                ['t' => 'Say no to feelings', 'img' => 0, 'embed' => 'Ddfrr6wseuW'],
                ['t' => 'Fear is temporary, regret is forever', 'img' => 0, 'embed' => 'DdYUe29xE3Y'],
                ['t' => 'Investor ko kya chahiye?', 'img' => 0, 'embed' => 'DdBKXzhxkiY'],
                ['t' => 'No risk no story', 'img' => 0, 'embed' => 'Dc8ARykxvJe'],
                ['t' => 'Hardships make you a man', 'img' => 0, 'embed' => 'Dc5ZqKlRvWm'],
                ['t' => 'Face your fears', 'img' => 0, 'embed' => 'Dc2-wmeRpEk'],
                ['t' => 'One decision can change your life', 'img' => 0, 'embed' => 'DcytofeR6TZ'],
                ['t' => 'Self-accountability zero', 'img' => 0, 'embed' => 'Dcsy6gWRmYg'],
                ['t' => 'No one is coming to save you', 'img' => 0, 'embed' => 'Dcp8fbHRT8s'],
                ['t' => 'Everything is possible', 'img' => 0, 'embed' => 'DcnYXsJOwZ-'],
                ['t' => 'Decide, commit, execute', 'img' => 0, 'embed' => 'DckyOeIgy0t'],
                ['t' => 'Go beyond your limits', 'img' => 0, 'embed' => 'DciU8tzx4fz'],
                ['t' => '5 year study plan', 'img' => 0, 'embed' => 'DcfqUjyxZrw'],
                ['t' => 'Create 25th hour', 'img' => 0, 'embed' => 'DcDqOCuxuHv'],
                ['t' => 'Think like an owner, not a worker', 'img' => 0, 'embed' => 'Dcah-Fyx4hf'],
                ['t' => 'Built by tough days', 'img' => 0, 'embed' => 'DcX787zxs7W'],
                ['t' => 'You have to work', 'img' => 0, 'embed' => 'DcLCWJpxmRN'],
                ['t' => 'Your family depends on you', 'img' => 0, 'embed' => 'Db-PNXPAr-L'],
                ['t' => 'Stay humble, table always turns', 'img' => 0, 'embed' => 'DdGOgkuRFmH'],
                ['t' => 'The 1% mindset', 'img' => 0, 'embed' => 'DdDumC1uX_S'],
                ['t' => 'Think beyond yourself', 'img' => 0, 'embed' => 'Dc-hDICx8TN'],
            ],
            'principles' => [
                [
                    't' => 'Back the founder before the idea',
                    'd' => 'Markets change and ideas evolve. The founder\'s ability to adapt, learn, and execute is what creates lasting value.',
                ],
                [
                    't' => 'Read people, not presentations',
                    'd' => 'A pitch deck shows preparation. A conversation reveals conviction, honesty, and the ability to handle pressure.',
                ],
                ['t' => 'Execution beats prediction', 'd' => 'The best opportunities are discovered by people who consistently execute, test, and improve.'],
                [
                    't' => 'Capital follows clarity',
                    'd' => 'Investors do not just fund ideas. They fund founders who understand the problem, customer, and path forward.',
                ],
                [
                    't' => 'Think in decades, not quarters',
                    'd' => 'Great businesses are built through patience, discipline, and decisions that compound over time.',
                ],
                ['t' => 'The first customer teaches everything', 'd' => 'Real market feedback is more valuable than assumptions made inside a room.'],
                ['t' => 'Solve painful problems', 'd' => 'The strongest companies are built around problems people urgently want solved.'],
                [
                    't' => 'Distribution creates advantage',
                    'd' => 'A great product without reach remains invisible. Winning companies understand how customers discover them.',
                ],
                ['t' => 'Build systems, not dependence', 'd' => 'A business becomes valuable when processes work beyond one person\'s effort.'],
                ['t' => 'Protect your reputation', 'd' => 'Trust compounds faster than money. Every interaction becomes part of your long-term asset.'],
                [
                    't' => 'Speed matters in uncertainty',
                    'd' => 'You rarely have perfect information. Strong operators make decisions, learn quickly, and adjust.',
                ],
                ['t' => 'Stay close to the customer', 'd' => 'The market always speaks. Successful founders listen before they build.'],
                ['t' => 'Technology is leverage', 'd' => 'AI and emerging tools create opportunities, but only when combined with strong execution.'],
                [
                    't' => 'Ownership creates responsibility',
                    'd' => 'The best builders think like owners because they understand every decision has consequences.',
                ],
                ['t' => 'Learn before you scale', 'd' => 'Growth without understanding creates bigger problems. Master the fundamentals first.'],
                [
                    't' => 'Build relationships before you need them',
                    'd' => 'The strongest networks are created through genuine value, not last-minute requests.',
                ],
                ['t' => 'Choose discipline over motivation', 'd' => 'Motivation changes. Systems, habits, and consistency create progress.'],
                ['t' => 'Invest in your ability to adapt', 'd' => 'Markets change constantly. The ability to learn faster becomes a competitive advantage.'],
                [
                    't' => 'Understand downside before upside',
                    'd' => 'Smart decisions start by understanding what can go wrong before chasing what can go right.',
                ],
                ['t' => 'Build with integrity', 'd' => 'Short-term wins disappear. Reputation and trust determine long-term success.'],
                ['t' => 'Stay hungry after success', 'd' => 'Past achievements create experience, not permission to stop improving.'],
                ['t' => 'The founder sets the standard', 'd' => 'Teams often reflect the mindset, discipline, and ambition of the person leading them.'],
                ['t' => 'Focus creates momentum', 'd' => 'Too many priorities divide attention. Great companies concentrate on what matters most.'],
                ['t' => 'Conviction before consensus', 'd' => ''],
                ['t' => 'The market rewards patience', 'd' => ''],
                ['t' => 'Never confuse activity with progress', 'd' => ''],
                ['t' => 'Great teams attract capital', 'd' => ''],
                ['t' => 'Cash flow is freedom', 'd' => ''],
                ['t' => 'The customer is the ultimate judge', 'd' => ''],
                ['t' => 'Build quietly, deliver loudly', 'd' => ''],
                ['t' => 'Every setback contains data', 'd' => ''],
                ['t' => 'The right partnership changes everything', 'd' => ''],
                ['t' => 'Small advantages compound', 'd' => ''],
                ['t' => 'Avoid shortcuts that damage foundations', 'd' => ''],
                ['t' => 'Your network is your multiplier', 'd' => ''],
                ['t' => 'Make decisions with first principles', 'd' => ''],
                ['t' => 'Momentum is earned daily', 'd' => ''],
                ['t' => 'Build products people remember', 'd' => ''],
                ['t' => 'Stay adaptable in changing markets', 'd' => ''],
                ['t' => 'The best opportunities look impossible early', 'd' => ''],
                ['t' => 'Strong founders create strong cultures', 'd' => ''],
                ['t' => 'Protect your time like capital', 'd' => ''],
                ['t' => 'Learn from every market cycle', 'd' => ''],
                ['t' => 'Long-term thinking creates unfair advantages', 'd' => ''],
                ['t' => 'The next opportunity starts with preparation', 'd' => ''],
            ],
        ],
        'podcast' => [
            'eyebrow' => 'Conversations',
            'episodes' => [
                [
                    't' => 'How Saad Made His Millions',
                    'src' => 'Business Breakdown',
                    'd' => 'Two operators unpack how Saad built his multi-million dollar empire.',
                    'yt' => 'gz5yMEZzrsM',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'The Money Game',
                    'src' => 'Sapiens Experience with Uzair',
                    'd' => 'An entrepreneur’s honest take on chasing capital and conviction.',
                    'yt' => 'iUn7TTXfTmk',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'H University’s Free Courses',
                    'src' => 'The Nakash Khan Show',
                    'd' => 'The mission to create six million jobs, one free course at a time.',
                    'yt' => 'kCjLfHKCPJ4',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'Unfiltered Talk',
                    'src' => 'First Time, With Saad Hashmani',
                    'd' => 'An unguarded first-time conversation on fame, ego, and the climb.',
                    'yt' => 'MVXua-u3SW4',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'Mindset To Become Millionaire',
                    'src' => 'Episode #41',
                    'd' => 'The daily mindset shifts behind a self-made fortune.',
                    'yt' => 'wAnStcdDy-w',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'Making It Big In The US',
                    'src' => 'Junaid Akram’s Podcast · #136',
                    'd' => 'A kid from the streets of Karachi, building a business in Houston.',
                    'yt' => 'Wk0Ch-UzEEY',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'Rise To Power In US, Part 1',
                    'src' => 'Two Flags, One Ambition',
                    'd' => 'Comparing the road to power in Pakistan and the United States.',
                    'yt' => 'xbcH7a01Qc0',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'Blueprint Of A Millionaire Mind, Part 1',
                    'src' => 'Sapiens Experience with Uzair',
                    'd' => 'Reverse-engineering the mindset behind the money.',
                    'yt' => 'xZrWIopkOkY',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'How To Become A Millionaire Living In Pakistan',
                    'src' => 'Money Loves Me · Episode 37',
                    'd' => 'Building wealth without ever leaving home.',
                    'yt' => 'yKeCu0Rn-xA',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'Ghurbat Seh Lena, Zillat Na Sehna',
                    'src' => 'Mufti Tariq Masood Podcast',
                    'd' => 'A candid conversation on poverty, dignity, and self-respect.',
                    'yt' => 'ZAU6U6WGwGY',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'I Made A Free University',
                    'src' => 'EON',
                    'd' => 'The story behind building an education platform that costs nothing.',
                    'yt' => 'zYObkTusSEc',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'Million Dollar Journey',
                    'src' => 'Founder To Founder',
                    'd' => 'Tracing the milestones from first dollar to first million.',
                    'yt' => 'A7AaahqIfHQ',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'Main Logo Ko Ameer Kerdonga',
                    'src' => 'Featuring Saad Hashmani',
                    'd' => 'A promise to help others build their own path to wealth.',
                    'yt' => 'qbVuRiarIbc',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'The Mindset That Made Him A Millionaire In America',
                    'src' => 'How Does It Work? · Tecno',
                    'd' => 'Breaking down the discipline behind an immigrant success story.',
                    'yt' => 'qhC3EDWL9SQ',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'Pakistan, India Ya Bangladesh: Sabke Liye!',
                    'src' => 'A Message For The Region',
                    'd' => 'Why the lessons of building a business apply across every border.',
                    'yt' => 'yDY7oO_HTj4',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'The Truth About My Cars, Money And Ego',
                    'src' => 'Talha Ahad Podcast · Ep 154',
                    'd' => 'An honest reckoning with fame, wealth, and what it costs.',
                    'yt' => 'dfKuHC0YpXY',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'Blueprint Of Success',
                    'src' => 'Sapiens Experience with Uzair',
                    'd' => 'A working framework for building something that lasts.',
                    'yt' => 'fnp1dEWSpbs',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'Millionaire Mindset',
                    'src' => 'Episode 203',
                    'd' => 'What actually separates the 1% from everyone else.',
                    'yt' => 'tVilzpqgHJo',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'Funding For AI Startups In Pakistan',
                    'src' => 'The Next Frontier',
                    'd' => 'A look at where early-stage capital is heading next.',
                    'yt' => '5cltPCLP7ec',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'The Real Hashmani Success Philosophy',
                    'src' => 'Unpacked',
                    'd' => 'Separating the myth from the method behind the name.',
                    'yt' => 'CiJ_uX3VPGU',
                    'img' => 0,
                    'thumb' => 0,
                ],
                [
                    't' => 'Shaping Mindsets',
                    'src' => 'Houston To The World',
                    'd' => 'How one perspective shift changes everything that follows.',
                    'yt' => 'dxbStzijYtg',
                    'img' => 0,
                    'thumb' => 0,
                ],
            ],
        ],
        'receipts' => [
            'eyebrow' => 'Community Of Builders',
            'heading' => 'Word of Mouth',
            'stats' => [
                'all' => [
                    ['1.1M+', 'TikTok followers'],
                    ['40M+', 'TikTok likes'],
                    ['176K+', 'Facebook community'],
                ],
                'google' => [
                    ['4.9', 'Avg rating'],
                    ['320+', 'Reviews'],
                    ['98%', 'Positive'],
                ],
                'instagram' => [
                    ['Active', 'Community'],
                    ['High', 'Engagement'],
                    ['Daily', 'Stories'],
                ],
                'facebook' => [
                    ['176K', 'Followers'],
                    ['4.8', 'Page rating'],
                    ['2.1K', 'Shares'],
                ],
                'tiktok' => [
                    ['1.1M', 'Followers'],
                    ['40.4M', 'Likes'],
                    ['Daily', 'Posts'],
                ],
                'twitter' => [
                    ['1.9K', 'Followers'],
                    ['2012', 'On X since'],
                    ['Active', 'Threads'],
                ],
            ],
            'filter_labels' => ['google' => 'G', 'instagram' => 'IG', 'facebook' => 'f', 'tiktok' => 'TT', 'twitter' => 'X'],
            'testimonials_left' => [
                [
                    'platform' => 'tiktok',
                    'stars' => 5,
                    'text' => 'The playbook changed how I read my own numbers. First profitable quarter came right after.',
                    'name' => 'Bilal Ahmed',
                    'role' => 'Founder, Nexcart',
                    'avatar' => 0,
                    'media' => 0,
                    'yt' => '',
                ],
                [
                    'platform' => 'google',
                    'stars' => 5,
                    'text' => 'Education first, hype never. The discipline is the whole edge.',
                    'name' => 'Usman Tariq',
                    'role' => 'Independent Trader',
                    'avatar' => 0,
                    'media' => 0,
                    'yt' => 'ScMzIvxBSi4',
                ],
                [
                    'platform' => 'tiktok',
                    'stars' => 5,
                    'text' => 'He showed up in the dip, not just the win. Founders remember that.',
                    'name' => 'Daniyal Sheikh',
                    'role' => 'Founder, Cartly',
                    'avatar' => 0,
                    'media' => 0,
                    'yt' => 'ScMzIvxBSi4',
                ],
                [
                    'platform' => 'google',
                    'stars' => 5,
                    'text' => 'Underwrote the downside with us before we ever talked returns. Real operator.',
                    'name' => 'Hamza Ali',
                    'role' => 'Ops Lead, Skyline',
                    'avatar' => 0,
                    'media' => 0,
                    'yt' => '',
                ],
                [
                    'platform' => 'facebook',
                    'stars' => 5,
                    'text' => 'Clean cap table advice early saved every round that came after.',
                    'name' => 'Omar Raza',
                    'role' => 'Founder, Stackly',
                    'avatar' => 0,
                    'media' => 0,
                    'yt' => 'ScMzIvxBSi4',
                ],
                [
                    'platform' => 'twitter',
                    'stars' => 5,
                    'text' => 'Conviction before consensus. I have watched him be early and right, repeatedly.',
                    'name' => 'Faizan Yusuf',
                    'role' => 'Angel Investor',
                    'avatar' => 0,
                    'media' => 0,
                    'yt' => '',
                ],
            ],
            'testimonials_right' => [
                [
                    'platform' => 'instagram',
                    'stars' => 5,
                    'text' => 'Saad backed us before the thesis had a name. That conviction is rare.',
                    'name' => 'Sara Khan',
                    'role' => 'CEO, Bloom Labs',
                    'avatar' => 0,
                    'media' => 0,
                    'yt' => '',
                ],
                [
                    'platform' => 'facebook',
                    'stars' => 4,
                    'text' => 'Straight answers in one meeting. A fast no that saved us months.',
                    'name' => 'Ayesha Malik',
                    'role' => 'COO, Finovate',
                    'avatar' => 0,
                    'media' => 0,
                    'yt' => '',
                ],
                [
                    'platform' => 'instagram',
                    'stars' => 5,
                    'text' => 'The H University gave my team skills we could not afford anywhere else.',
                    'name' => 'Zara Iqbal',
                    'role' => 'Growth Marketer',
                    'avatar' => 0,
                    'media' => 0,
                    'yt' => '',
                ],
                [
                    'platform' => 'twitter',
                    'stars' => 4,
                    'text' => 'Local knowledge is his alpha. He sees Pakistan the way founders live it.',
                    'name' => 'Mariam Farooq',
                    'role' => 'Product Analyst',
                    'avatar' => 0,
                    'media' => 0,
                    'yt' => '',
                ],
                [
                    'platform' => 'tiktok',
                    'stars' => 5,
                    'text' => 'Learned more from one thread than a year of courses. Then he replied.',
                    'name' => 'Nida Aslam',
                    'role' => 'Creator',
                    'avatar' => 0,
                    'media' => 0,
                    'yt' => '',
                ],
                [
                    'platform' => 'google',
                    'stars' => 5,
                    'text' => 'He protects the founder, not the optics. That trust compounds.',
                    'name' => 'Hina Shah',
                    'role' => 'Founder, Petal',
                    'avatar' => 0,
                    'media' => 0,
                    'yt' => '',
                ],
            ],
        ],
        'contact' => [
            'eyebrow' => 'Partner With Saad',
            'heading' => 'Build Something',
            'heading_accent' => 'Meaningful.',
            'description' => 'Whether you are building a startup, exploring partnerships, or looking for practical mentorship, share your vision.',
            'email' => 'contact@saadhashmani.com',
            'location' => 'Houston, Texas · Access by request',
            'form_plugin' => '',
            'cf7_form_id' => 0,
            'recaptcha_site' => '',
            'recaptcha_secret' => '',
            'form_types' => ['Business inquiry', 'Review', 'General query', 'Work with me'],
            'default_type' => 'General query',
            'social' => [
                'x' => 'https://x.com/saadahashmani',
                'facebook' => 'https://www.facebook.com/saadahashmani/',
                'instagram' => 'https://www.instagram.com/saadahashmani/',
                'tiktok' => 'https://www.tiktok.com/@saadhashmaniofficial',
                'linkedin' => 'https://www.linkedin.com/in/saad-hashmani-b252418a',
            ],
        ],
    ];
    return $d;
}
