<?php
/** Custom cursor and gallery lightbox. */
defined('ABSPATH') || exit;
$v = $args;
?>
<div data-cur="lens" aria-hidden="true" style="position: fixed; left: 0; top: 0; width: 34px; height: 34px; border-radius: 999px; border: 1px solid var(--line-strong,rgba(255,255,255,.14)); box-shadow: inset 0 1px 0 rgba(255,255,255,.08),0 10px 34px rgba(0,0,0,.3); background: rgba(255,255,255,.045); -webkit-backdrop-filter: blur(4px) saturate(1.2); backdrop-filter: blur(4px) saturate(1.2); z-index: 210; pointer-events: none; opacity: 0; overflow: hidden; will-change: transform,width,height; transition: width .3s cubic-bezier(.16,1,.3,1),height .3s cubic-bezier(.16,1,.3,1),border-radius .3s cubic-bezier(.16,1,.3,1),opacity .3s cubic-bezier(.16,1,.3,1),background .3s cubic-bezier(.16,1,.3,1);"><div data-cur="icon" style="position: absolute; inset: 0; display: none; align-items: center; justify-content: center; color: var(--glow,#f6f5f2);"></div><svg data-cur="ring" viewBox="0 0 90 90" width="90" height="90" style="position: absolute; inset: 0; display: none; overflow: visible; transform-origin: center; animation: vault-spin 9s linear infinite;"><defs><path id="cur-circ" d="M45,45 m-34,0 a34,34 0 1,1 68,0 a34,34 0 1,1 -68,0" fill="none"></path></defs><text style="font-family: var(--font-mono,monospace); font-weight: 500; font-size: 8.5px; letter-spacing: .14em; text-transform: uppercase; fill: var(--glow,#f6f5f2);"><textPath data-cur-ringtext="true" href="#cur-circ" startOffset="0" textLength="213" lengthAdjust="spacing"></textPath></text></svg></div>
<div data-cur="dot" aria-hidden="true" style="position: fixed; left: 0; top: 0; width: 6px; height: 6px; border-radius: 999px; background: var(--glow,#f6f5f2); z-index: 212; pointer-events: none; opacity: 0; will-change: transform,width,height,border-radius; transition: opacity .3s,width .22s cubic-bezier(.16,1,.3,1),height .22s cubic-bezier(.16,1,.3,1),border-radius .22s;"></div>

<div data-gallery-lb="true" style="position: fixed; inset: 0; z-index: 66; display: none; opacity: 0; transition: opacity .3s cubic-bezier(.16,1,.3,1); align-items: center; justify-content: center; padding: clamp(24px,6vw,90px); background: rgba(3,4,5,.82); -webkit-backdrop-filter: blur(16px) saturate(1.05); backdrop-filter: blur(16px) saturate(1.05);"><img alt="" loading="lazy" decoding="async" fetchpriority="low" style="max-width: min(880px,92vw); max-height: calc(86*var(--vh,1vh)); object-fit: contain; border-radius: 16px; border: 1px solid var(--line-strong,rgba(255,255,255,.14)); box-shadow: 0 50px 130px rgba(0,0,0,.6); display: block;"><button data-gallery-prev="true" type="button" aria-label="<?php echo esc_attr(__('Previous image', 'saadhashmani')); ?>" style="position: absolute; left: clamp(14px,3vw,36px); top: 50%; transform: translateY(-50%); width: 46px; height: 46px; display: flex; align-items: center; justify-content: center; padding: 0; border: 1px solid var(--line-strong,rgba(255,255,255,.14)); border-radius: 999px; background: rgba(11,11,12,.55); backdrop-filter: blur(8px); color: var(--tx,#f4f4f5); cursor: pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M15 18l-6-6 6-6"></path></svg></button><button data-gallery-next="true" type="button" aria-label="<?php echo esc_attr(__('Next image', 'saadhashmani')); ?>" style="position: absolute; right: clamp(14px,3vw,36px); top: 50%; transform: translateY(-50%); width: 46px; height: 46px; display: flex; align-items: center; justify-content: center; padding: 0; border: 1px solid var(--line-strong,rgba(255,255,255,.14)); border-radius: 999px; background: rgba(11,11,12,.55); backdrop-filter: blur(8px); color: var(--tx,#f4f4f5); cursor: pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M9 6l6 6-6 6"></path></svg></button><button data-gallery-close="true" type="button" aria-label="<?php echo esc_attr(__('Close', 'saadhashmani')); ?>" style="position: absolute; top: clamp(20px,calc(4*var(--vh,1vh)),40px); right: clamp(20px,4vw,40px); width: 40px; height: 40px; border-radius: 999px; border: 1px solid var(--line-strong,rgba(255,255,255,.14)); background: rgba(11,11,12,.55); -webkit-backdrop-filter: blur(8px); backdrop-filter: blur(8px); color: var(--tx,#f4f4f5); font-size: 16px; line-height: 1; display: flex; align-items: center; justify-content: center; cursor: pointer;">✕</button></div>
