<?php
/** The Receipts: testimonial columns, platform filter and stats. */
defined('ABSPATH') || exit;
$v = $args;
?>
<section id="receipts" data-sec6="true" aria-labelledby="receipts-title" style="position: fixed; inset: 0; z-index: 3; opacity: 0; pointer-events: none; will-change: opacity,transform;">
<?php if (!empty($v['receipts']['show_cards'])) : ?><div data-testi-col="true" data-side="left" style="position: absolute; top: clamp(72px,calc(12*var(--vh,1vh)),140px); bottom: clamp(28px,calc(5*var(--vh,1vh)),56px); left: clamp(20px,3.2vw,52px); width: clamp(316px,27vw,404px); overflow: hidden; padding: 8px clamp(14px,1.3vw,22px); box-sizing: border-box; pointer-events: auto; cursor: grab; -webkit-mask-image: linear-gradient(180deg,transparent,#000 9%,#000 91%,transparent); mask-image: linear-gradient(180deg,transparent,#000 9%,#000 91%,transparent);"><div data-testi-track="true" style="will-change: transform;"><?php for ($dup = 0; $dup < 2; $dup++) : foreach ($v['receipts']['left'] as $c) : get_template_part('template-parts/testimonial-card', null, $c); endforeach; endfor; ?></div></div></div>
<div data-testi-col="true" data-side="right" style="position: absolute; top: clamp(72px,calc(12*var(--vh,1vh)),140px); bottom: clamp(28px,calc(5*var(--vh,1vh)),56px); right: clamp(20px,3.2vw,52px); width: clamp(316px,27vw,404px); overflow: hidden; padding: 8px clamp(14px,1.3vw,22px); box-sizing: border-box; pointer-events: auto; cursor: grab; -webkit-mask-image: linear-gradient(180deg,transparent,#000 9%,#000 91%,transparent); mask-image: linear-gradient(180deg,transparent,#000 9%,#000 91%,transparent);"><div data-testi-track="true" style="will-change: transform;"><?php for ($dup = 0; $dup < 2; $dup++) : foreach ($v['receipts']['right'] as $c) : get_template_part('template-parts/testimonial-card', null, $c); endforeach; endfor; ?></div></div></div><?php endif; ?>
<div style="position: absolute; left: 50%; transform: translateX(-50%); top: clamp(44px,calc(7*var(--vh,1vh)),80px); width: min(480px,62vw); text-align: center; z-index: 2; pointer-events: none; display: flex; flex-direction: column; align-items: center; gap: 10px;"><div data-eyebrow="true" style="font-family: var(--font-mono,monospace); font-weight: 400; font-size: 12px; letter-spacing: .16em; text-transform: uppercase; color: var(--tx-faint,#6b6b73);"><?php echo esc_html($v['receipts']['eyebrow']); ?></div><h2 id="receipts-title" style="margin: 0; font-family: var(--font-grotesk,sans-serif); font-weight: 500; text-transform: none; font-size: clamp(26px,3vw,44px); line-height: .98; letter-spacing: -.01em; color: var(--tx,#f4f4f5); text-shadow: 0 0 44px var(--glow-soft,rgba(246,245,242,.14));"><?php echo esc_html($v['receipts']['heading']); ?></h2></div><div style="position: absolute; left: 50%; transform: translateX(-50%); top: clamp(150px,calc(20*var(--vh,1vh)),196px); display: flex; gap: 12px; z-index: 2; pointer-events: auto;"><?php foreach ($v['receipts']['labels'] as $plat => $label) : ?><button data-testi-plat="true" data-p="<?php echo esc_attr($plat); ?>" type="button" aria-label="<?php echo esc_attr(sh_platform_name($plat)); ?>" aria-pressed="false" style="display: flex; align-items: center; justify-content: center; width: 44px; height: 44px; padding: 0; border: 1px solid var(--line-strong,rgba(255,255,255,.14)); border-radius: 999px; background: rgba(3,4,5,.4); backdrop-filter: blur(10px); -webkit-backdrop-filter: blur(10px); cursor: pointer; font-family: var(--font-body,sans-serif); font-weight: 600; font-size: 12px; letter-spacing: .02em; color: var(--tx-faint,#6b6b73); transition: color .26s,border-color .26s,background .26s;"><?php echo esc_html($label); ?></button><?php endforeach; ?></div>
<div data-testi-stats="true" style="position: absolute; left: 50%; transform: translateX(-50%); bottom: clamp(34px,calc(6*var(--vh,1vh)),64px); display: flex; gap: clamp(30px,5vw,72px); z-index: 2; pointer-events: none;"><?php foreach ($v['receipts']['stats_all'] as $st) : ?><div style="text-align: center;"><div data-stat-n="true" style="font-family: var(--font-body,sans-serif); font-weight: 400; font-size: clamp(26px,2.4vw,38px); line-height: 1; color: var(--glow,#f6f5f2); text-shadow: 0 0 22px rgba(255,255,255,.14);"><?php echo esc_html($st[0]); ?></div><div data-stat-l="true" style="margin-top: 8px; font-family: var(--font-body,sans-serif); font-weight: 500; font-size: 11px; letter-spacing: .16em; text-transform: uppercase; color: var(--tx-faint,#6b6b73);"><?php echo esc_html($st[1]); ?></div></div><?php endforeach; ?></div>
<div data-testi-lightbox="true" style="position: fixed; inset: 0; z-index: 20; display: none; align-items: center; justify-content: center; padding: clamp(20px,5vw,80px); background: rgba(3,4,5,.9); backdrop-filter: blur(14px); -webkit-backdrop-filter: blur(14px); pointer-events: auto;">
<button data-testi-close="true" type="button" aria-label="<?php echo esc_attr(__('Close', 'saadhashmani')); ?>" style="position: absolute; top: clamp(20px,calc(4*var(--vh,1vh)),40px); right: clamp(20px,4vw,44px); width: 46px; height: 46px; display: flex; align-items: center; justify-content: center; padding: 0; border: 1px solid var(--line-strong,rgba(255,255,255,.14)); border-radius: 999px; background: rgba(3,4,5,.5); cursor: pointer;"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="var(--tx,#f4f4f5)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18M6 6l12 12"></path></svg></button>
<div style="position: relative; width: min(1040px,92vw); aspect-ratio: 16/9; border: 1px solid rgba(255,255,255,.1); border-radius: 14px; overflow: hidden; box-shadow: 0 40px 90px rgba(0,0,0,.6);"><iframe data-testi-frame="true" title="Review" allow="autoplay; encrypted-media" allowfullscreen="" style="width: 100%; height: 100%; border: 0; display: block;"></iframe></div>
</div>
</section>
