<?php
/** Podcast ring and player. */
defined('ABSPATH') || exit;
$v = $args;
?>
<section id="podcast" data-sec5="true" aria-labelledby="podcast-title" style="position: fixed; inset: 0; z-index: 3; opacity: 0; pointer-events: none; will-change: opacity,transform;">
<div data-pod-stage="true" style="position: absolute; left: 0; right: 0; top: clamp(48px,calc(6*var(--vh,1vh)),86px); height: clamp(172px,calc(26*var(--vh,1vh)),262px); perspective: 1500px; perspective-origin: 50% 50%; pointer-events: none;">
<div data-pod-ring="true" style="position: absolute; inset: 0; transform-style: preserve-3d; pointer-events: auto;"><?php foreach ($v['podcast']['episodes'] as $pi => $ep) : ?><div data-pod-card="true" data-i="<?php echo (int) $pi; ?>" style="position: absolute; left: 50%; top: 50%; width: clamp(102px,9.2vw,136px); height: clamp(148px,13vw,190px); margin: 0; border-radius: 16px; overflow: hidden; border: 1px solid var(--line-strong,rgba(255,255,255,.14)); box-shadow: 0 30px 60px rgba(0,0,0,.55); cursor: pointer; will-change: transform,opacity; transform: translate(-50%,-50%); backface-visibility: hidden;"><?php if ($ep['thumb']) : ?><img src="<?php echo esc_url($ep['thumb']); ?>"<?php echo $ep['srcset']; ?> alt="<?php echo esc_attr($ep['t']); ?>" loading="lazy" decoding="async" fetchpriority="low" style="width: 100%; height: 100%; object-fit: cover; display: block;"><?php endif; ?><div style="position: absolute; inset: 0; background: linear-gradient(180deg,rgba(3,4,5,0) 55%,rgba(3,4,5,.5) 100%);"></div></div><?php endforeach; ?></div>
</div>
<div style="position: absolute; left: 0; right: 0; top: clamp(348px,calc(56*var(--vh,1vh)),600px); text-align: center; padding: 0 clamp(24px,6vw,80px); pointer-events: none;">

<div data-pod-src="true" data-eyebrow="true" style="font-family: var(--font-mono,monospace); font-weight: 400; font-size: 12px; letter-spacing: .16em; text-transform: uppercase; color: var(--tx-faint,#6b6b73);"><?php echo esc_html($v['podcast']['eyebrow']); ?></div><h3 id="podcast-title" data-pod-title="true" style="margin: 16px 0 0; font-family: var(--font-grotesk,sans-serif); font-weight: 500; font-size: clamp(30px,4vw,60px); line-height: .98; letter-spacing: -.01em; color: var(--glow,#f6f5f2);"><?php echo esc_html($v['podcast']['first']['t']); ?></h3>
<p data-pod-desc="true" style="margin: 16px auto 0; font-family: var(--font-body,sans-serif); font-weight: 400; font-size: 15px; line-height: 1.6; color: var(--tx-muted,#a1a1aa); white-space: nowrap; width: auto; height: auto; text-align: center;"><?php echo esc_html($v['podcast']['first']['d']); ?></p>
</div>
<div style="position: absolute; left: 50%; transform: translateX(-50%); bottom: clamp(40px,calc(8*var(--vh,1vh)),80px); width: min(560px,80vw); display: flex; flex-direction: column; gap: 20px; pointer-events: auto;">
<div style="display: flex; align-items: center; justify-content: center; gap: 26px;">
<button data-pod-prev="true" type="button" aria-label="<?php echo esc_attr(__('Previous', 'saadhashmani')); ?>" style="width: 44px; height: 44px; display: flex; align-items: center; justify-content: center; padding: 0; border: 1px solid var(--line-strong,rgba(255,255,255,.14)); border-radius: 999px; background: rgba(11,11,12,.55); backdrop-filter: blur(10px); -webkit-backdrop-filter: blur(10px); cursor: pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--tx,#f4f4f5)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="m15 18-6-6 6-6"></path></svg></button>
<button data-pod-play="true" type="button" aria-label="<?php echo esc_attr(__('Play episode', 'saadhashmani')); ?>" style="width: 62px; height: 62px; display: flex; align-items: center; justify-content: center; padding: 0; border: 1px solid var(--glow,#f6f5f2); border-radius: 999px; background: var(--glow,#f6f5f2); backdrop-filter: blur(10px); -webkit-backdrop-filter: blur(10px); cursor: pointer; transition: transform .34s ease-in,background 260ms,box-shadow 260ms;"><svg width="22" height="22" viewBox="0 0 24 24" fill="var(--bg,#0b0b0c)" stroke="none"><path d="M8 5v14l11-7z"></path></svg></button>
<button data-pod-next="true" type="button" aria-label="<?php echo esc_attr(__('Next', 'saadhashmani')); ?>" style="width: 44px; height: 44px; display: flex; align-items: center; justify-content: center; padding: 0; border: 1px solid var(--line-strong,rgba(255,255,255,.14)); border-radius: 999px; background: rgba(11,11,12,.55); backdrop-filter: blur(10px); -webkit-backdrop-filter: blur(10px); cursor: pointer;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--tx,#f4f4f5)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="m9 18 6-6-6-6"></path></svg></button>
</div>
<div style="display: flex; align-items: center; gap: 16px;">
<div data-pod-track="true" style="position: relative; flex: 1; height: 3px; border-radius: 999px; background: rgba(255,255,255,.14); cursor: pointer; overflow: hidden;"><div data-pod-prog="true" style="position: absolute; left: 0; top: 0; bottom: 0; width: 0%; background: var(--glow,#f6f5f2);"></div></div>
<button data-pod-speed="true" type="button" aria-label="<?php echo esc_attr(__('Playback speed', 'saadhashmani')); ?>" style="font-family: var(--font-mono,monospace); font-weight: 500; font-size: 12px; letter-spacing: .12em; text-transform: uppercase; color: var(--tx,#f4f4f5); padding: 7px 14px; border: 1px solid var(--line-strong,rgba(255,255,255,.14)); border-radius: 999px; background: rgba(11,11,12,.5); cursor: pointer; white-space: nowrap;">1x</button>
</div>
</div>
<div data-pod-lightbox="true" style="position: fixed; inset: 0; z-index: 20; display: none; align-items: center; justify-content: center; padding: clamp(20px,5vw,80px); background: rgba(3,4,5,.9); backdrop-filter: blur(14px); -webkit-backdrop-filter: blur(14px); pointer-events: auto;">
<button data-pod-close="true" type="button" aria-label="<?php echo esc_attr(__('Close', 'saadhashmani')); ?>" style="position: absolute; top: clamp(28px,calc(5*var(--vh,1vh)),54px); right: clamp(28px,5vw,58px); z-index: 3; width: 46px; height: 46px; display: flex; align-items: center; justify-content: center; padding: 0; border: 1px solid var(--line-strong,rgba(255,255,255,.14)); border-radius: 999px; background: rgba(11,11,12,.6); cursor: pointer;"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="var(--tx,#f4f4f5)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18M6 6l12 12"></path></svg></button>
<div style="position: relative; width: min(1040px,92vw); aspect-ratio: 16/9; border: 1px solid var(--line,rgba(255,255,255,.08)); border-radius: 14px; overflow: hidden; box-shadow: 0 40px 90px rgba(0,0,0,.6); background: #000;">
<img data-pod-poster="true" alt="" loading="lazy" decoding="async" fetchpriority="low" style="position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover; display: block;">
<button data-pod-lightbox-play="true" type="button" aria-label="<?php echo esc_attr(__('Play video', 'saadhashmani')); ?>" style="position: absolute; left: 50%; top: 50%; transform: translate(-50%,-50%); width: 74px; height: 74px; display: flex; align-items: center; justify-content: center; padding: 0; border: 1px solid var(--glow,#f6f5f2); border-radius: 999px; background: rgba(3,4,5,.45); backdrop-filter: blur(8px); -webkit-backdrop-filter: blur(8px); cursor: pointer;"><svg width="26" height="26" viewBox="0 0 24 24" fill="var(--glow,#f6f5f2)"><path d="M8 5v14l11-7z"></path></svg></button>
<iframe data-pod-frame="true" referrerpolicy="strict-origin-when-cross-origin" title="Podcast" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen="" style="position: absolute; inset: 0; width: 100%; height: 100%; border: 0; display: none;"></iframe>
</div>
</div>
</section>
