<?php
/** Ventures carousel. */
defined('ABSPATH') || exit;
$v = $args;
?>
<section id="ventures" data-sec3="true" aria-label="<?php echo esc_attr($v['nav'][2]['label']); ?>" style="position: fixed; inset: 0; z-index: 3; opacity: 0; pointer-events: none; will-change: opacity,transform;">
<?php foreach ($v['ventures'] as $i => $ven) : ?>
<article data-vslide="true" data-i="<?php echo (int) $i; ?>" style="position: absolute; inset: 0; opacity: 0; pointer-events: none; transition: opacity 1100ms var(--ease-brand,cubic-bezier(.16,1,.3,1));">
<div style="position: absolute; inset: 0; background: radial-gradient(125% 110% at 50% 50%,rgba(11,11,12,0) 26%,rgba(11,11,12,.5) 78%,rgba(11,11,12,.8) 100%); pointer-events: none;"></div>
<div style="position: absolute; left: clamp(52px,7vw,120px); top: calc(clamp(92px,calc(13*var(--vh,1vh)),150px) - clamp(30px,calc(5*var(--vh,1vh)),64px)); font-family: var(--font-grotesk,sans-serif); font-weight: 500; font-size: clamp(150px,22vw,320px); line-height: .8; color: rgba(255,255,255,.04); letter-spacing: -.01em; pointer-events: none;" aria-hidden="true"><?php echo esc_html(str_pad($i + 1, 2, '0', STR_PAD_LEFT)); ?></div>
<div data-vinner="true" style="position: absolute; inset: 0; opacity: 0; transform: translateX(14px); transition: opacity 1100ms var(--ease-brand,cubic-bezier(.16,1,.3,1)),transform 1200ms var(--ease-brand,cubic-bezier(.16,1,.3,1));">
<div style="position: absolute; left: clamp(52px,7vw,120px); top: clamp(92px,calc(13*var(--vh,1vh)),150px); display: flex; flex-direction: column; gap: 20px; max-width: 56vw; pointer-events: none;">
<div style="display: flex; align-items: center; gap: 16px;"><?php if ($ven['logo']) : ?><img src="<?php echo esc_url($ven['logo']); ?>"<?php echo $ven['logo_srcset']; ?> alt="<?php echo esc_attr($ven['title']); ?>" loading="lazy" decoding="async" fetchpriority="low" style="height: 44px; width: auto; max-width: 190px; object-fit: contain; display: block;"><?php endif; ?><span data-eyebrow="true" style="font-family: var(--font-mono,monospace); font-weight: 400; font-size: 12px; letter-spacing: .14em; text-transform: uppercase; color: var(--tx-muted,#a1a1aa);"><?php echo esc_html($ven['eyebrow']); ?></span></div>
<h2 style="margin: 0; font-family: var(--font-grotesk,sans-serif); font-weight: 500; text-transform: none; font-size: clamp(46px,6.4vw,102px); line-height: .94; letter-spacing: -.01em; color: var(--tx,#f4f4f5); text-shadow: 0 0 48px var(--glow-soft,rgba(246,245,242,.14));"><?php echo esc_html($ven['title']); ?></h2>
</div>
<div style="position: absolute; right: clamp(52px,7vw,120px); top: clamp(92px,calc(13*var(--vh,1vh)),150px); display: grid; grid-template-columns: auto auto; column-gap: clamp(22px,2.8vw,48px); row-gap: clamp(16px,calc(2.4*var(--vh,1vh)),26px); justify-content: end; max-width: 44vw; pointer-events: none;"><?php foreach ($ven['stats'] as $vs) : ?><div style="text-align: right;"><div style="font-family: var(--font-grotesk,sans-serif); font-weight: 500; font-variant-numeric: tabular-nums; font-size: clamp(26px,2.4vw,38px); line-height: 1; letter-spacing: -.01em; color: var(--tx,#f4f4f5);"><?php echo esc_html($vs['value']); ?></div><div style="margin-top: 8px; font-family: var(--font-mono,monospace); font-weight: 400; font-size: 11px; letter-spacing: .14em; text-transform: uppercase; color: var(--tx-faint,#6b6b73);"><?php echo esc_html($vs['label']); ?></div></div><?php endforeach; ?></div>
<div style="position: absolute; left: clamp(52px,7vw,120px); bottom: clamp(52px,calc(9*var(--vh,1vh)),88px); display: flex; flex-direction: column; gap: 20px; max-width: 40ch; pointer-events: none;">
<p style="margin: 0; max-width: 40ch; font-family: var(--font-body,sans-serif); font-weight: 400; font-size: 15px; line-height: 1.62; color: var(--tx-muted,#a1a1aa);"><?php echo esc_html($ven['description']); ?></p>
<a href="<?php echo esc_url($ven['cta_url'] === '#' ? '#contact' : $ven['cta_url']); ?>"<?php if ($ven['cta_url'] !== '#') : ?> target="_blank" rel="noopener noreferrer" data-ext-cta="true"<?php endif; ?> style="display: inline-flex; align-items: center; gap: 10px; pointer-events: auto; width: max-content; font-family: var(--font-mono,monospace); font-weight: 500; font-size: 11px; letter-spacing: .12em; text-transform: uppercase; white-space: nowrap; color: var(--tx,#f4f4f5); text-decoration: none; padding: 13px 22px; border: 1px solid var(--line-strong,rgba(255,255,255,.14)); border-radius: 999px; transition: color 400ms cubic-bezier(.32,.72,0,1),background 400ms cubic-bezier(.32,.72,0,1),border-color 400ms cubic-bezier(.32,.72,0,1);"><?php echo esc_html($ven['cta_label']); ?><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M7 17 17 7M7 7h10v10"></path></svg></a>
</div>
<div style="position: absolute; right: clamp(52px,7vw,120px); bottom: clamp(52px,calc(9*var(--vh,1vh)),88px); display: flex; flex-direction: column; gap: 16px; align-items: flex-end; pointer-events: none;">
<?php if (!empty($ven['gallery'])) : ?>
<div data-vgallery="<?php echo (int) $i; ?>" style="display: flex; flex-direction: column; align-items: flex-end; gap: 10px; pointer-events: auto;">
<div data-vg-viewport="true" style="overflow: hidden; width: calc(clamp(74px,7vw,104px)*3 + 24px);">
<div data-vg-track="true" style="display: flex; gap: 12px; transition: transform .4s cubic-bezier(.16,1,.3,1);">
<?php foreach ($ven['gallery'] as $gi => $g) : ?><div style="position: relative; flex: none; width: clamp(74px,7vw,104px); aspect-ratio: 1/1; padding: 5px; border: 1px solid var(--line,rgba(255,255,255,.08)); border-radius: 14px; background: var(--bg-raised,#121214);"><div style="position: relative; width: 100%; height: 100%; border-radius: 9px; overflow: hidden; background: var(--bg-inset,#08080a); box-shadow: inset 0 1px 0 rgba(255,255,255,.06);"><img data-vg-img="true" src="<?php echo esc_url($g['thumb']); ?>"<?php echo $g['srcset']; ?> data-full="<?php echo esc_url($g['full']); ?>" alt="<?php echo esc_attr(sprintf(__('%1$s image %2$d', 'saadhashmani'), $ven['title'], $gi + 1)); ?>" loading="lazy" decoding="async" fetchpriority="low" style="width: 100%; height: 100%; object-fit: cover; display: block; cursor: pointer;"></div></div><?php endforeach; ?>
</div>
</div>
</div>
<?php endif; ?>
<?php if (!empty($v['partners'])) : ?><div style="display: flex; flex-direction: column; align-items: flex-start; align-self: flex-start; gap: 10px;"><div style="font-family: var(--font-mono,monospace); font-weight: 400; font-size: 11px; letter-spacing: .16em; text-transform: uppercase; color: var(--tx-faint,#6b6b73);"><?php echo esc_html(__('Partners', 'saadhashmani')); ?></div><div data-pmarquee="true" style="overflow: hidden; width: clamp(160px,17vw,220px); -webkit-mask-image: linear-gradient(90deg,#000 0,#000 72%,transparent); mask-image: linear-gradient(90deg,#000 0,#000 72%,transparent); pointer-events: auto;"><div data-ptrack="true" style="display: flex; align-items: center; gap: 32px; width: max-content; animation: vault-marquee 26s linear infinite;"><?php for ($dup = 0; $dup < 2; $dup++) : foreach ($v['partners'] as $pl) : ?><img data-plogo="true" src="<?php echo esc_url($pl['url']); ?>"<?php echo $pl['srcset']; ?> alt="<?php echo esc_attr($pl['alt']); ?>" loading="lazy" decoding="async" fetchpriority="low" style="height: <?php echo (int) $pl['h']; ?>px; width: auto; display: block; flex: none;"><?php endforeach; endfor; ?></div></div></div><?php endif; ?>
</div>
</div>
</article>
<?php endforeach; ?>
<div style="position: absolute; left: clamp(20px,3vw,44px); top: 50%; transform: translateY(-50%); display: flex; flex-direction: column; align-items: flex-start; gap: 20px; z-index: 3;">
<button data-vprev="true" type="button" aria-label="<?php echo esc_attr(__('Previous venture', 'saadhashmani')); ?>" style="width: 42px; height: 42px; display: flex; align-items: center; justify-content: center; padding: 0; border: 1px solid var(--line-strong,rgba(255,255,255,.14)); border-radius: 999px; background: rgba(11,11,12,.45); backdrop-filter: blur(10px); -webkit-backdrop-filter: blur(10px); cursor: pointer; pointer-events: auto;"><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="var(--tx,#f4f4f5)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="m18 15-6-6-6 6"></path></svg></button>
<div data-vcur="true" style="display: none; font-family: var(--font-mono,monospace); font-size: 13px; letter-spacing: .08em; color: var(--tx,#f4f4f5);">01</div>
<div style="display: flex; flex-direction: column; gap: 16px;"><?php foreach ($v['ventures'] as $di => $dv) : ?><button data-vdot="true" data-i="<?php echo (int) $di; ?>" type="button" aria-label="<?php echo esc_attr($dv['title']); ?>" style="display: flex; align-items: center; gap: 11px; background: none; border: none; padding: 0; cursor: pointer; pointer-events: auto;"><span data-vdot-n="true" style="font-family: var(--font-mono,monospace); font-weight: 400; font-size: 11px; letter-spacing: .1em; color: var(--tx-faint,#6b6b73); transition: color 260ms;"><?php echo esc_html(str_pad($di + 1, 2, '0', STR_PAD_LEFT)); ?></span><span data-vdot-l="true" style="display: block; width: 20px; height: 1px; background: var(--line-strong,rgba(255,255,255,.14)); transition: width 300ms,background 300ms;"></span></button><?php endforeach; ?></div>
<button data-vnext="true" type="button" aria-label="<?php echo esc_attr(__('Next venture', 'saadhashmani')); ?>" style="width: 42px; height: 42px; display: flex; align-items: center; justify-content: center; padding: 0; border: 1px solid var(--line-strong,rgba(255,255,255,.14)); border-radius: 999px; background: rgba(11,11,12,.45); backdrop-filter: blur(10px); -webkit-backdrop-filter: blur(10px); cursor: pointer; pointer-events: auto;"><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="var(--tx,#f4f4f5)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="m6 9 6 6 6-6"></path></svg></button>
</div>
</section>
