<?php
/** One testimonial card. $args = the resolved card. */
defined('ABSPATH') || exit;
$c = $args;
?>
<div data-testi-card="true" data-plat="<?php echo esc_attr($c['platform']); ?>" style="border: 1px solid rgba(255,255,255,.1); border-radius: 18px; background: linear-gradient(155deg,rgba(255,255,255,.05),rgba(255,255,255,.02)); backdrop-filter: blur(18px) saturate(140%); -webkit-backdrop-filter: blur(18px) saturate(140%); box-shadow: inset 0 1px 0 rgba(255,255,255,.16),0 24px 50px rgba(0,0,0,.42); padding: 14px; margin-bottom: 14px; transform-style: preserve-3d; transition: transform .3s var(--ease-brand,cubic-bezier(.22,.61,.36,1)),box-shadow .3s,opacity .3s; will-change: transform;">
<?php if ($c['media'] || $c['yt']) : ?><div style="position: relative; width: 100%; aspect-ratio: 16/9; border-radius: 10px; overflow: hidden; margin-bottom: 10px;"><?php if ($c['media']) : ?><img src="<?php echo esc_url($c['media']); ?>" alt="" loading="lazy" decoding="async" style="width: 100%; height: 100%; object-fit: cover; display: block;"><?php endif; ?><?php if ($c['yt']) : ?><div style="position: absolute; inset: 0; background: rgba(3,4,5,.32);"></div><button data-testi-play="true" data-yt="<?php echo esc_attr($c['yt']); ?>" type="button" aria-label="<?php echo esc_attr(sprintf(__('Play review from %s', 'saadhashmani'), $c['name'])); ?>" style="position: absolute; left: 50%; top: 50%; transform: translate(-50%,-50%); width: 48px; height: 48px; display: flex; align-items: center; justify-content: center; padding: 0; border: 1px solid var(--glow,#f6f5f2); border-radius: 999px; background: rgba(3,4,5,.4); backdrop-filter: blur(8px); -webkit-backdrop-filter: blur(8px); cursor: pointer; pointer-events: auto;"><svg width="18" height="18" viewBox="0 0 24 24" fill="var(--glow,#f6f5f2)"><path d="M8 5v14l11-7z"></path></svg></button><?php endif; ?></div><?php endif; ?>
<div style="display: flex; gap: 3px; margin-bottom: 9px;" role="img" aria-label="<?php echo esc_attr(sprintf(__('%d out of 5 stars', 'saadhashmani'), $c['stars'])); ?>"><?php for ($s = 0; $s < 5; $s++) : ?><svg width="13" height="13" viewBox="0 0 24 24" fill="<?php echo $s < $c['stars'] ? 'var(--glow,#f6f5f2)' : 'none'; ?>" stroke="var(--glow,#f6f5f2)" stroke-width="1.2" style="display: block;"><path d="m12 2 3 6.5 7 .7-5.2 4.7 1.5 6.9L12 17.8 5.2 20.8l1.5-6.9L1.5 9.2l7-.7z"></path></svg><?php endfor; ?></div>
<p style="margin: 0 0 11px; font-family: var(--font-body,sans-serif); font-weight: 400; font-size: 13px; line-height: 1.5; color: var(--tx,#f4f4f5);"><?php echo esc_html($c['text']); ?></p>
<div style="display: flex; align-items: center; gap: 12px;">
<div style="position: relative; width: 32px; height: 32px; border-radius: 999px; overflow: hidden; flex: none; border: 1px solid rgba(255,255,255,.12);"><?php if ($c['avatar']) : ?><img src="<?php echo esc_url($c['avatar']); ?>" alt="<?php echo esc_attr($c['name']); ?>" loading="lazy" decoding="async" style="width: 100%; height: 100%; object-fit: cover; display: block;"><?php endif; ?></div>
<div style="flex: 1; min-width: 0;"><div style="font-family: var(--font-body,sans-serif); font-weight: 500; font-size: 14px; color: var(--tx,#f4f4f5);"><?php echo esc_html($c['name']); ?></div><div style="font-family: var(--font-body,sans-serif); font-weight: 400; font-size: 12px; letter-spacing: .02em; color: var(--tx-faint,#6b6b73);"><?php echo esc_html($c['role']); ?></div></div>
<div style="display: flex; align-items: center; justify-content: center; width: 26px; height: 26px; border-radius: 999px; border: 1px solid rgba(255,255,255,.12); font-family: var(--font-mono,monospace); font-weight: 500; font-size: 11px; letter-spacing: .08em; text-transform: uppercase; color: var(--tx-muted,#a1a1aa); flex: none;" title="<?php echo esc_attr(sh_platform_name($c['platform'])); ?>"><?php echo esc_html($c['badge']); ?></div>
</div>
</div>
